### ISSUE TITLE
Instructions for using Valine?

### ISSUE THREAD

**Issue by psharma04** [Litreily/hexo-theme-snark#3]
How to use Valine comment system?

**Comment by Litreily** [comment]
you can modify file `_config.yml`
```
# comment system
valine: ## https://valine.js.org
  enable: true ## If you want to use Valine comment system, please set the value to true.
  appid: ## Your LeanCloud application App ID, e.g. pRBBL2JR4N7kLEGojrF0MsSs-gzGzoHsz
  appkey: ## Your LeanCloud application App Key, e.g. tjczHpDfhjYDSYddzymYK1JJ
  notify: false ## Mail notifier, see https://github.com/xCss/Valine/wiki/Valine-评论系统中的邮件提醒设置
  verify: false ## Validation code.
  placeholder: "ヾﾉ≧∀≦)o Come on, say something..." ## Comment box placeholders.
  avatar: 'identicon' ## Gravatar type, see https://github.com/xCss/Valine/wiki/avatar-setting-for-valine
  pageSize: 10 ## Number of comments per page.
  guest_info: nick,mail,link ## Attributes of reviewers.
```

you can follow document [quick start](https://valine.js.org/quickstart.html) to get `appid` and `appkey`

**Comment by psharma04** [comment]
Can I set language to English?

**Comment by Litreily** [comment]
of course, I just add language support for this, you can modify `_config.yml` `valine.lang`  as below.
``` yml
valine: ## https://valine.js.org
  enable: false ## If you want to use Valine comment system, please set the value to true.
  appid: ## Your LeanCloud application App ID, e.g. pRBBL2JR4N7kLEGojrF0MsSs-gzGzoHsz
  appkey: ## Your LeanCloud application App Key, e.g. tjczHpDfhjYDSYddzymYK1JJ
  lang: en ## Language, e.g. zh-cn, en
```
